on:
  workflow_dispatch:

name: build-linux-rt

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3

      - name: build kernel
        run: ./run.sh

      - name: check built kernel
        run: ls -lh debs

      - name: Upload kernel as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel debian packages
          path: debs
